name: Build SimplePyBLE

on:
  workflow_call:

jobs:

  build-sdist:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add Version Suffix
        uses: ./.github/actions/setup-version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install dependencies
        run: pip install build

      - name: Build source distribution
        run: python3 -m build --sdist

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: simplepyble-sdist
          path: dist/*.tar.gz


  build-wheels:
    runs-on: ${{ matrix.config.runner-os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { runner-os: ubuntu-22.04, os: linux, arch: x86_64 }
          - { runner-os: ubuntu-22.04, os: linux, arch: i686 }
          - { runner-os: ubuntu-22.04, os: linux, arch: aarch64 }
          - { runner-os: macos-14, os: macos, arch: x86_64 }
          - { runner-os: macos-14, os: macos, arch: universal2 }
          - { runner-os: macos-14, os: macos, arch: arm64 }
          - { runner-os: windows-2022, os: windows, arch: AMD64 }
          - { runner-os: windows-2022, os: windows, arch: x86 }
          - { runner-os: windows-2022, os: windows, arch: ARM64 }

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add Version Suffix
        uses: ./.github/actions/setup-version

      - name: Set up QEMU
        if: matrix.config.os == 'linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_ALL_LINUX: "yum update -y && yum group install -y \"Development Tools\" && yum install -y dbus-devel"
          CIBW_ARCHS: ${{ matrix.config.arch }}
          CIBW_SKIP: "*musllinux_* pp* cp36-* cp37-*"
          MACOSX_DEPLOYMENT_TARGET: "11.0"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: simplepyble-${{ matrix.config.os }}-${{ matrix.config.arch }}
          path: wheelhouse/*.whl

  publish:
    needs: [build-sdist, build-wheels]
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:

      - name: Install dependencies
        run: pip install twine

      - name: "Download Python Wheels"
        uses: actions/download-artifact@v4
        with:
          pattern: simplepyble-*-*
          path: wheels
          merge-multiple: true

      - name: "Download Python source distribution"
        uses: actions/download-artifact@v4
        with:
          name: simplepyble-sdist
          path: sdist

      - name: Check packages
        run: twine check wheels/*.whl

      - name: Check source distribution
        run: twine check sdist/simplepyble*.tar.gz

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheels
          skip-existing: true
          attestations: false # Broken, see: https://github.com/pypa/gh-action-pypi-publish/issues/166

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: sdist
          skip-existing: true
          attestations: false # Broken, see: https://github.com/pypa/gh-action-pypi-publish/issues/166


  # tests:
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - name: Clone Repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         fetch-tags: true

  #     - name: Add Version Suffix
  #       uses: ./.github/actions/setup-version

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: 3.11
  #         cache: "pip"

  #     - name: Install dependencies
  #       run: pip install -r simplepyble/requirements.txt

  #     - name: Install SimplePyBLE with Plain flavor
  #       run: python setup.py install --plain

  #     - name: Run PyTest
  #       run: pytest
  #       working-directory: ./simplepyble/test